#Database
POSTGRESQL_USERNAME: user
POSTGRESQL_PASSWORD: udemekendrick
POSTGRESQL_HOST: postgresdb
POSTGRESQL_PORT: 5432
POSTGRESQL_DATABASE: privdocdatabase

#Server
CONTAINER_PORT: 8085
ACTIVE_PROFILE: prod

#Email Config
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: udemekendrick@gmail.com
EMAIL_PASSWORD: psvervddyqjnysrn
VERIFY_EMAIL_HOST: http://localhost:8085